Projeto/apps/apps/urls.py
from django.urls import include, path
from django.contrib import admin

import theme.views

urlpatterns = [
    path('', theme.views.home),
    path('catalogo/', include('catalogo.urls')),

    # Enable built-in authentication views
    path('accounts/', include('django.contrib.auth.urls')),    
    # Enable built-in admin interface
    path('admin/', admin.site.urls),
]

Projeto/apps/catalogo/urls.py
from django.urls import path

from . import views

app_name = 'catalogo'

urlpatterns = [
  path('', views.principal, name='principal'),
  path('lote/', views.lista_lote, name='lista_lote'),
  path('lote/new/', views.cria_lote, name='cria_lote'),
  path('lote/<int:pk>/', views.detalha_lote, name='detalha_lote'),
  path('lote/pay/<int:pk>/', views.paga_lote, name='paga_lote'),
  path('lote/edit/<int:pk>/', views.atualiza_lote, name='atualiza_lote'),
  path('lote/insert/<int:pk>/', views.insere_valores, name='insere_valores'),
  path('lote/delete/<int:pk>/', views.deleta_lote, name='deleta_lote'),
  path('leilao/', views.lista_leilao, name='lista_leilao'),
  path('leilao/new/<int:id_lote>/', views.cria_leilao, name='cria_leilao'),
  path('leilao/<int:pk>/', views.detalha_leilao, name='detalha_leilao'),
  path('leilao/pay/<int:pk>/', views.paga_leilao, name='paga_leilao'),
  path('leilao/edit/<int:pk>/', views.atualiza_leilao, name='atualiza_leilao'),
  path('leilao/init/<int:pk>/', views.inicia_leilao, name='inicia_leilao'),
  path('leilao/cancel/<int:pk>/', views.cancela_leilao, name='cancela_leilao'),
  path('leilao/end/<int:pk>/', views.encerra_leilao, name='encerra_leilao'),
  path('leilao/delete/<int:pk>/', views.deleta_leilao, name='deleta_leilao'),
  path('lance/new/<int:id_leilao>/', views.faz_lance, name='faz_lance'),
  path('relatorio/new/<int:id_leilao>/', views.gera_relatorio, name='gera_relatorio'),
  path('relatorio/desempenho/<int:id_leilao>/', views.gera_relatorio_desempenho, name='gera_relatorio_desempenho'),
  path('relatorio/faturamento/<int:id_leilao>/', views.gera_relatorio_faturamento, name='gera_relatorio_faturamento'),
  path('relatorio/desempenho/', views.gera_relatorio_desempenho_geral, name='gera_relatorio_desempenho_geral'),
  path('relatorio/faturamento/', views.gera_relatorio_faturamento_geral, name='gera_relatorio_faturamento_geral'),
  path('relatorio/desempenho/download', views.gera_relatorio_pdf_desempenho_geral, name='gera_relatorio_pdf_desempenho_geral'),
  path('relatorio/faturamento/download', views.gera_relatorio_pdf_faturamento_geral, name='gera_relatorio_pdf_faturamento_geral'),
]

Projeto/apps/catalogo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.conf import settings

class CustomUser(User):
    TIPO_USUARIO_CHOICES = (
        ("C", "Comprador"),
        ("L", "Leiloeiro"),
        ("V", "Vendedor")
    )

    tipo_usuario = models.CharField(max_length=1, choices=TIPO_USUARIO_CHOICES, blank=False, null=False)

class Lote(models.Model):
    ESTADO_CHOICES = (
        ("N", "Novo"),
        ("S", "Seminovo"),
        ("U", "Usado")
    )

    ESTADO_DICT = {"N": "Novo", "S": "Seminovo", "U": "Usado"}

    name = models.CharField(max_length=200, verbose_name='Nome do Lote')
    descricao = models.CharField(max_length=1000, verbose_name='Descrição dos Itens do Lote')
    estado = models.CharField(max_length=1, choices=ESTADO_CHOICES, blank=False, null=False, verbose_name='Estado do Lote')
    taxa_de_comissao = models.FloatField()
    valor_minimo_de_lote = models.FloatField(verbose_name='Valor Inicial do Lote')
    valor_minimo_de_reserva = models.FloatField(verbose_name='Valor Mínimo de Reserva')
    valor_minimo_por_lance = models.FloatField(verbose_name='Valor Mínimo por Lance')

    pago = models.BooleanField()

    vendedor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalogo:detalha_lote', kwargs={'pk': self.pk})

class Leilao(models.Model):
    STATUS_CHOICES = (
        ("N", "Não iniciado"),
        ("A", "Ativo"),
        ("C", "Cancelado"),
        ("F", "Finalizado")
    )

    STATUS_DICT = {"N": "Não iniciado", "A": "Ativo", "C": "Cancelado", "F": "Finalizado"}

    name = models.CharField(max_length=200, verbose_name='Nome do Leilão')
    periodoInicio = models.DateTimeField(verbose_name='Dia e Horário de Início do Leilão')
    periodoFinal = models.DateTimeField(verbose_name='Dia e Horário de Encerramento do Leilão')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, blank=False, null=False)

    pago = models.BooleanField()

    lote = models.ForeignKey(Lote, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalogo:detalha_leilao', kwargs={'pk': self.pk})

class Lance(models.Model):
    valor = models.FloatField(verbose_name='Valor do Lance')

    comprador = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    leilao = models.ForeignKey(Leilao, on_delete=models.CASCADE)

    def __str__(self):
        return '{0} - R${1}'.format(self.comprador.username, self.valor)

Projeto/apps/catalogo/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ValidationError
from django.utils.timezone import utc
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm
from django.http import HttpResponse
from django import forms

from datetime import datetime, timezone, timedelta
import pytz

from .utils import cria_usuarios, checa_status_leiloes
from .models import CustomUser, Lote, Leilao, Lance
from .permissions import comprador_required, vendedor_required, leiloeiro_required, vendedor_or_leiloeiro_required, get_tipo_usuario
from .html_to_pdf import render_to_pdf

# Forms
class LoteForm(ModelForm):
    class Meta:
        model = Lote
        fields = ['name', 'descricao', 'estado', 'valor_minimo_de_reserva']

        widgets = {
            'name': forms.TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Nome'
                }),
            'descricao': forms.TextInput(attrs={
                'class': "form-control", 
                'placeholder': 'Descrição'
                }),
            'valor_minimo_de_reserva': forms.NumberInput(attrs={
                'class': "form-control", 
                'placeholder': 'Valor Mínimo de Reserva'
                })
        }
     
    def clean_valor_minimo_de_reserva(self):
        # valor_minimo_de_lote = self.data['valor_minimo_de_lote']
        valor_minimo_de_reserva = self.cleaned_data['valor_minimo_de_reserva']

        # Checa se o valor mínimo de reserva é superior a zero.
        if float(valor_minimo_de_reserva) <= 0:
            raise ValidationError(_('Valor mínimo de reserva deve ser superior a 0.'))

        return valor_minimo_de_reserva

class LeilaoForm(ModelForm):
    class Meta:
        model = Leilao
        fields = ['name', 'periodoInicio', 'periodoFinal']
        
        widgets = {
            'name': forms.TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Nome'
                }),
            'periodoInicio': forms.TextInput(attrs={
                'class': "form-control", 
                'placeholder': 'Exemplo: 2022-01-25 18:00:00'
                }),
            'periodoFinal': forms.TextInput(attrs={
                'class': "form-control", 
                'placeholder': 'Exemplo: 2022-01-29 18:00:00'
                })
        }

    def clean_periodoInicio(self):
        periodoInicio = self.cleaned_data['periodoInicio']
        periodoFinal = self.data['periodoFinal']

        if type(periodoInicio) == str:
            try:
                periodoInicio_dt = datetime.strptime(periodoInicio, '%Y-%m-%d %H:%M:%S')
            except ValueError:
                raise ValidationError(_('Formato incorreto de data. Utilizar YY-MM-DD HH:mm:ss'))
        else:
            periodoInicio_dt = periodoInicio
        
        if type(periodoFinal) == str:
            try:
                periodoFinal_dt = datetime.strptime(periodoFinal, '%Y-%m-%d %H:%M:%S')
            except ValueError:
                raise ValidationError(_('Formato incorreto de data. Utilizar YY-MM-DD HH:mm:ss'))
        else:
            periodoFinal_dt = periodoFinal

        # Checa se o início do período é posterior ao horário atual.
        if periodoInicio_dt.replace(tzinfo=pytz.timezone('America/Sao_Paulo')) < datetime.now(pytz.timezone('America/Sao_Paulo')).replace(tzinfo=pytz.timezone('America/Sao_Paulo')):
            raise ValidationError(_('Início do período do leilão deve ser posterior ao horário atual.'))

        # Checa se o início do período é anterior ao final do período.
        if periodoInicio_dt.replace(tzinfo=pytz.timezone('America/Sao_Paulo')) >= periodoFinal_dt.replace(tzinfo=pytz.timezone('America/Sao_Paulo')):
            raise ValidationError(_('Início do período do leilão deve ser anterior ao final do período do leilão.'))

        return periodoInicio

    def clean_periodoFinal(self):
        periodoInicio = self.data['periodoInicio']
        periodoFinal = self.cleaned_data['periodoFinal']

        if type(periodoInicio) == str:
            try:
                periodoInicio_dt = datetime.strptime(periodoInicio, '%Y-%m-%d %H:%M:%S')
            except ValueError:
                raise ValidationError(_('Formato incorreto de data. Utilizar YY-MM-DD HH:mm:ss'))
        else:
            periodoInicio_dt = periodoInicio
        
        if type(periodoFinal) == str:
            try:
                periodoFinal_dt = datetime.strptime(periodoFinal, '%Y-%m-%d %H:%M:%S')
            except ValueError:
                raise ValidationError(_('Formato incorreto de data. Utilizar YY-MM-DD HH:mm:ss'))
        else:
            periodoFinal_dt = periodoFinal

        # Checa se o início do período é posterior ao horário atual.
        if periodoFinal_dt.replace(tzinfo=pytz.timezone('America/Sao_Paulo')) < datetime.now(pytz.timezone('America/Sao_Paulo')).replace(tzinfo=pytz.timezone('America/Sao_Paulo')) + timedelta(days=1):
            raise ValidationError(_('Final do período do leilão deve ser posterior ao horário atual mais um dia.'))

        # Checa se o início do período é anterior ao final do período.
        if periodoFinal_dt.replace(tzinfo=pytz.timezone('America/Sao_Paulo')) < periodoInicio_dt.replace(tzinfo=pytz.timezone('America/Sao_Paulo')) + timedelta(days=1):
            raise ValidationError(_('Final do período do leilão deve ser posterior ao início do período do leilão mais um dia.'))

        return periodoFinal

class LanceForm(ModelForm):
    class Meta:
        model = Lance
        fields = ['valor']

    def __init__(self, *args,**kwargs):
        self.leilao = kwargs.pop('leilao')
        super(LanceForm, self).__init__(*args, **kwargs)

    def clean_valor(self):
        valor = self.cleaned_data['valor']

        # Checa se o valor é superior a zero.
        if float(valor) <= 0:
            raise ValidationError(_('Valor deve ser superior a 0.'))

        v_min_lote = self.leilao.lote.valor_minimo_de_lote

        # Checa se o valor é superior ao valor minimo de lote.
        if float(valor) < v_min_lote:
            raise ValidationError(_(f'Valor deve ser igual ou superior ao valor mínimo de lote: \
                                    R${v_min_lote}.'))

        lances = sorted(list(Lance.objects.filter(leilao__id=self.leilao.id)), key=lambda t: t.valor, reverse=True)
        if lances:
            valor_maior_lance = lances[0].valor
        else:
            valor_maior_lance = -10000

        v_por_lance = self.leilao.lote.valor_minimo_por_lance

        # Checa se o valor é superior ao valor minimo de lote.
        if float(valor) < valor_maior_lance + v_por_lance:
            raise ValidationError(_(f'Valor deve ser superior ao maior lance atual mais o valor mínimo por lance: \
                                    R${valor_maior_lance + v_por_lance}.'))

        return valor

# funções dos lotes
@login_required
def principal(request, template_name='catalogo/principal.html'):
    
    lances = Lance.objects.all()

    cria_usuarios()

    data = {}
    data['lista_de_leiloes_ativos'] = Leilao.objects.filter(status='A')
    data['tipo_usuario'] = get_tipo_usuario(request.user)

    # Pegar maior lance depois

    return render(request, template_name, data)

# funções dos lotes
@login_required
def lista_lote(request, template_name='catalogo/lista_lote.html'):
    if request.user.is_superuser or get_tipo_usuario(request.user) == 'L':
        lotes = Lote.objects.all()
    else:
        lotes = Lote.objects.filter(vendedor=request.user)

    data = {}
    data['lista_de_lotes'] = lotes
    data['lista_de_lotes_disponiveis'] = []
    for lote in lotes:
        if not Leilao.objects.filter(lote = lote).exclude(status='C'):
            data['lista_de_lotes_disponiveis'].append(lote)
            
    data['tipo_usuario'] = get_tipo_usuario(request.user)

    return render(request, template_name, data)

@login_required
def detalha_lote(request, pk, template_name='catalogo/detalha_lote.html'):
    if request.user.is_superuser or get_tipo_usuario(request.user) == 'L':
        lote= get_object_or_404(Lote, pk=pk)
    else:
        lote= get_object_or_404(Lote, pk=pk, vendedor=request.user)

    data = {}
    data['lote'] = lote
    data['tipo_usuario'] = get_tipo_usuario(request.user)
    data['estado'] = lote.ESTADO_DICT[lote.estado]

    return render(request, template_name, data)

@login_required
@vendedor_required
def cria_lote(request, template_name='catalogo/lote_form.html'):
    form = LoteForm(request.POST or None)
    if form.is_valid():
        lote = form.save(commit=False)
        lote.vendedor = request.user

        lote.valor_minimo_de_lote = 0
        lote.valor_minimo_por_lance = 0
        lote.pago = False

        if lote.valor_minimo_de_reserva <= 1000:
            lote.taxa_de_comissao = 1/100
        elif lote.valor_minimo_de_reserva <= 10000:
            lote.taxa_de_comissao = 2/100
        elif lote.valor_minimo_de_reserva <= 50000:
            lote.taxa_de_comissao = 3/100
        elif lote.valor_minimo_de_reserva <= 100000:
            lote.taxa_de_comissao = 4/100
        else:
            lote.taxa_de_comissao = 5/100

        lote.save()
        return redirect('catalogo:detalha_lote', pk=lote.id)
    return render(request, template_name, {'form':form})

@login_required
@vendedor_required
def paga_lote(request, pk, template_name='catalogo/pagamento.html'):
    if request.user.is_superuser or get_tipo_usuario(request.user) == 'L':
        lote= get_object_or_404(Lote, pk=pk)
    else:
        lote= get_object_or_404(Lote, pk=pk, vendedor=request.user)

    valor = lote.valor_minimo_de_reserva * lote.taxa_de_comissao

    data = {}
    data['valor'] = valor
    data['lote'] = lote

    if request.method == "POST":
        lote.pago = True

        lote.save()

Projeto/apps/catalogo/templates/catalogo/detalha_leilao.html
{% extends "base.html" %}

{% block content %}

<h2 class="titulo-leilao"><a href="{% url 'catalogo:detalha_leilao' leilao.id %}">{{ leilao.name }}</a></h2>

<h5 class="periodo">{{ leilao.periodoInicio }} - {{ leilao.periodoFinal }}</h5>

<div class="detalha-lote">
    <table>
        <tr>
            <td><b>Nome</b></td>
            <td>{{ leilao.lote.name }}</td>
        </tr>
        <tr>
            <td><b>Descrição</b></td>
            <td>{{ leilao.lote.descricao }}</td>
        </tr>
        <tr>
            <td><b>Estado</b></td>
            <td>{{ estado }}</td>
        </tr>
        <tr>
            <td><b>Vendedor</b></td>
            <td>{{ leilao.lote.vendedor.username }}</td>
        </tr>
        <tr>
            <td><b>Status do Leilão</b></td>
            <td>{{ status }}</td>
        </tr>
        <tr>
            <td><b>Valor Inicial do Lote</b></td>
            <td>R$ {{ leilao.lote.valor_minimo_de_lote }}</td>
        </tr>
        <tr>
            <td><b>Valor Mínimo por Lance</b></td>
            <td>R$ {{ leilao.lote.valor_minimo_por_lance }}</td>
        </tr>
        {% if tipo_usuario == 'V' or tipo_usuario == 'L' or tipo_usuario == 'A' %}
        <tr>
            <td><b>Valor Mínimo de Reserva</b></td>
            <td>R$ {{ leilao.lote.valor_minimo_de_reserva }}</td>
        </tr>
        <tr>
            <td><b>Taxa de Comissão do Vendedor</b></td>
            <td>{{ leilao.lote.taxa_de_comissao }}</td>
        </tr>
        {% endif %}
    </table>
    
    {% if leilao.status != 'N' %}
    <h3>Lances:</h3>
    <table>
        <tr>
            <th>Valor</th>
            <th>Comprador</th>
        </tr>
        {% for lance in lista_de_lances %}
        {% if lance.leilao.id == leilao.id %}
        <tr>
            <td>R$ {{ lance.valor }}</td>
            <td>{{ lance.comprador.username }}</td>
        </tr>
        
        {% endif %}
        {% endfor %}
        
    </table>

    {% endif %}
    
    <div class="detalha-lote-botoes">
        {% if leilao.status == 'N' %}
        {% if tipo_usuario == 'L' or tipo_usuario == 'A' %}
        <div class="detalha-lote-botao-central">
            <a href="{% url 'catalogo:inicia_leilao' leilao.id %}"><p class="small-button">Iniciar Leilão</p></a>
        </div>
        {% endif %}
        {% endif %}
        {% if leilao.status == 'A' %}
        {% if tipo_usuario == 'C' or tipo_usuario == 'A' %}
        <div class="detalha-lote-botao-central">
            <a href="{% url 'catalogo:faz_lance' leilao.id %}"><p class="small-button">Fazer Lance</p></a>
        </div>
        {% endif %}
        {% if tipo_usuario == 'L' or tipo_usuario == 'A' %}
        <div class="detalha-lote-botao-central">
            <a href="{% url 'catalogo:cancela_leilao' leilao.id %}"><p class="small-button">Cancelar Leilão</p></a>
        </div>
        {% endif %}
        {% if tipo_usuario == 'L' or tipo_usuario == 'A' %}
        <div class="detalha-lote-botao-central">
            <a href="{% url 'catalogo:encerra_leilao' leilao.id %}"><p class="small-button">Finalizar Leilão</p></a>
        </div>
        {% endif %}
        {% endif %}
        {% if leilao.status == 'F' %}
        {% if leilao.pago != True and comprador == usuario and status %}
        <div class="detalha-lote-botao-central">
            <a href="{% url 'catalogo:paga_leilao' leilao.id %}"><p class="small-button">Pagar Lance do Leilão</p></a>
        </div>
        {% endif %}
        {% endif %}
        {% if leilao.status == 'F' or leilao.status == 'C' %}
        {% if tipo_usuario == 'L' or tipo_usuario == 'A' %}
        <div class="detalha-lote-botao-central">
            <a href="{% url 'catalogo:gera_relatorio' leilao.id %}"><p class="small-button">Gerar Relatório</p></a>
        </div>
        {% endif %}
        {% endif %}
        {% if tipo_usuario == 'L' or tipo_usuario == 'A' %}
        <div class="detalha-lote-botao-central">
            <a href="{% url 'catalogo:atualiza_leilao' leilao.id %}"><p class="small-button">Editar</p></a>
        </div>
        {% endif %}
        
        {% if tipo_usuario == 'A' %}
        <div class="detalha-lote-botao-central">
            <a href="{% url 'catalogo:deleta_leilao' leilao.id %}"><p class="small-button">Deletar</p></a>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

Projeto/apps/catalogo/templates/catalogo/detalha_lote.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'catalogo:detalha_lote' lote.id %}">Lote {{ lote.name }}</a></h2>

<div class="detalha-lote">
    <p class="item-title">{{ lote.name }}</p>
    <p class="item-description center"><i>{{ lote.descricao }}</i></p>
    <hr class="item-title-divider">
    <table>
        <tr>
            <td><b>Estado</b></td>
            <td>{{ estado }}</td>
        </tr>
        <tr>
            <td><b>Vendedor</b></td>
            <td>{{ lote.vendedor.username }}</td>
        </tr>
        <tr>
            <td><b>Valor mínimo de reserva</b></td>
            <td>R$ {{ lote.valor_minimo_de_reserva }}</td>
        </tr>
        <tr>
            <td><b>Taxa de Comissão</b></td>
            <td>{{ lote.taxa_de_comissao }}</td>
        </tr>
        <tr>
            <td><b>Pago</b></td>
            <td>{{ lote.pago }}</td>
        </tr>
        {% if lote.valor_minimo_de_lote != 0 %}
        <tr>
            <td><b>Valor Inicial do Lote</b></td>
            <td>R$ {{ lote.valor_minimo_de_lote }}</td>
        </tr>
        <tr>
            <td><b>Valor Mínimo por Lance:</b></td>
            <td>R$ {{ lote.valor_minimo_por_lance }}</td>
        </tr>
        {% endif %}
    </table>

    {% if lote.valor_minimo_de_lote == 0 %}
    <p class="item-description item-warning">É necessário que o leiloeiro preencha os valores de lote e por lance do lote.</p>
    {% endif %}


    <div class="detalha-lote-botoes">
        {% if tipo_usuario == 'L' or tipo_usuario == 'A' %}
        {% if lote.valor_minimo_de_lote != 0 and lote.pago == True %}
        <div class="detalha-lote-botao-lateral">
            <a href="{% url 'catalogo:cria_leilao' lote.id %}"><p class="small-button">Cria Leilão</p></a>
        </div>
        {% endif %}
        {% endif %}
        {% if tipo_usuario == 'V' or tipo_usuario == 'A' %}
        {% if lote.pago != True %}
        <div class="detalha-lote-botao-central">
            <a href="{% url 'catalogo:paga_lote' lote.id %}"><p class="small-button">Pagar Lote</p></a>
        </div>
        {% endif %}
        <div class="detalha-lote-botao-central">
            <a href="{% url 'catalogo:atualiza_lote' lote.id %}"><p class="small-button">Editar Detalhes</p></a>
        </div>
        {% endif %}
        {% if tipo_usuario == 'L' or tipo_usuario == 'A' %}
        {% if lote.pago == True %}
        <div class="detalha-lote-botao-central">
            <a href="{% url 'catalogo:insere_valores' lote.id %}"><p class="small-button">Inserir Valores</p></a>
        </div>
        {% endif %}
        {% endif %}
        <div class="detalha-lote-botao-lateral">
            <a href="{% url 'catalogo:deleta_lote' lote.id %}"><p class="small-button">Deletar</p></a>
        </div>
    </div>
</div>

{% endblock %}

Projeto/apps/catalogo/templates/catalogo/lista_lote_leilao.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'catalogo:lista_lote_leilao' %}">Lotes disponíveis</a></h2>

<ul>
    {% for lote in lista_de_lotes_disponiveis %}
    <li>{{ lote.name }}  ({{ lote.valor_minimo_de_lote }} Valor)
    <a href="{% url 'catalogo:cria_leilao' lote.id %}">Cria Leilão</a>
    <a href="{% url 'catalogo:atualiza_lote' lote.id %}">Editar</a>
    <a href="{% url 'catalogo:deleta_lote' lote.id %}">Deletar</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'catalogo:cria_lote' %}">Novo lote</a>


<h2><a href="{% url 'catalogo:lista_lote_leilao' %}">Leilões Ativos</a></h2> 

<ul>
    {% for leilao in lista_de_leiloes %}
    <li>{{ leilao.name }}
    <a href="{% url 'catalogo:faz_lance' leilao.id %}">Fazer Lance</a>
    <a href="{% url 'catalogo:atualiza_leilao' leilao.id %}">Editar</a>
    <a href="{% url 'catalogo:deleta_leilao' leilao.id %}">Deletar</a>
    <ul>
        <li>Lote: {{leilao.lote.name}}</li>
        <li>Descrição: {{leilao.lote.descricao}}</li>
    </ul>
    <ul>
        <li>Lances:</li>
        <ul>
            {% for lance in lista_de_lances %}
            {% if lance.leilao.id == leilao.id %}
            <li>Valor: {{ lance.valor }} - Comprador: {{ lance.comprador.username }}

            </li>
            {% endif %}
            {% endfor %}
        </ul>
    </ul>
    </li>
    {% endfor %}
</ul>

{% endblock %}

Projeto/apps/catalogo/templates/catalogo/principal.html
{% extends "base.html" %}

{% load filter %}

{% block content %}

<div class="buttons-wrapper">
    {% if tipo_usuario != 'C' %}
    <div class="button-item">
        <a href="{% url 'catalogo:lista_lote' %}"><p class="home-button">Ver seus Lotes</p></a>
    </div>
    {% endif %}

    <div class="button-item">
        <a href="{% url 'catalogo:lista_leilao' %}"><p class="home-button">Ver Leilões Ativos</p></a>
    </div>

    {% if tipo_usuario == 'L' or tipo_usuario == 'A' %}
    <div class="button-item">
        <a href="{% url 'catalogo:gera_relatorio_desempenho_geral' %}"><p class="home-button">Ver Relatório Geral de Desempenho</p></a>
    </div>
    <div class="button-item">
        <a href="{% url 'catalogo:gera_relatorio_faturamento_geral' %}"><p class="home-button">Ver Relatório Geral de Faturamento</p></a>
    </div>
    {% endif %}
</div>

<h2>Alguns Leilões Ativos:</h2>
<div class="items-wrapper">
    {% for leilao in lista_de_leiloes_ativos %}
    <div class="item">
        <p class="item-title">{{ leilao.name }}</p>
        <hr class="item-title-divider">
        <p class="item-description"><b>Lote:</b> {{leilao.lote.name}}</p>
        <p class="item-description"><i>{{leilao.lote.descricao}}</i></p>
        <hr class="item-title-divider">
        <p class="item-description"><b>Lance Vencedor:</b></p>
        {% if lista_de_lances|pega_lances_de_leilao:leilao.id|first %}
        <ul>
            <li>{{ lista_de_lances|pega_lances_de_leilao:leilao.id|first }}</li> 
        </ul>
        {% else %}
        <ul>
            <li>Não há lances.</li>
        </ul>
        {% endif %}

        <a href="{% url 'catalogo:detalha_leilao' leilao.id %}"><p class="small-button bottom-anchor">Ver Detalhes</p></a>
    </div>
    {% endfor %}
</div>

{% endblock %}